import { useMemo, useState } from "react";
import { EmptyState } from "./PageStates.jsx";

export default function EventsPage({ data }) {
  const [filters, setFilters] = useState({ severity: "all", decision: "all", layer: "all", ip: "" });
  const events = useMemo(() => (data.events || []).filter((event) => (filters.severity === "all" || event.severity === filters.severity) && (filters.decision === "all" || event.decision === filters.decision) && (!filters.ip || String(event.ip || event.sourceIp || "").includes(filters.ip))), [data.events, filters]);
  const update = (key) => (event) => setFilters((current) => ({ ...current, [key]: event.target.value }));
  return <section className="panel table-panel wide full-width"><div className="panel-title"><div><h2>Security events</h2><p>Filter why a request was delayed, queued or blocked</p></div><span>{events.length} events</span></div><div className="filter-row"><select aria-label="Severity filter" value={filters.severity} onChange={update("severity")}><option value="all">All severities</option>{["normal", "warning", "high", "critical"].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Decision filter" value={filters.decision} onChange={update("decision")}><option value="all">All decisions</option>{["allow", "limit", "delay", "queue", "drop", "alert"].map((value) => <option key={value}>{value}</option>)}</select><input aria-label="IP filter" value={filters.ip} onChange={update("ip")} placeholder="Filter source IP" /></div><div className="table-scroll"><table><thead><tr><th>Timestamp</th><th>Layer</th><th>Source IP</th><th>Endpoint</th><th>Severity</th><th>Decision</th><th>Reason</th><th>Request ID</th></tr></thead><tbody>{events.map((event, index) => <tr key={event.id || event.requestId || index}><td>{event.timestamp || "—"}</td><td>{event.layer || "Layer 7"}</td><td>{event.ip || event.sourceIp || "—"}</td><td>{event.endpoint || "—"}</td><td>{event.severity || "normal"}</td><td>{event.decision || "—"}</td><td>{event.reason || "—"}</td><td>{event.requestId || "—"}</td></tr>)}</tbody></table>{!events.length && <EmptyState label="No events match the current filters." />}</div></section>;
}
